# Site settings
title: thibaultcha
email: thibaultcha@me.com
description: >
  Thibault Charbonnier, developer. Open-source, iOS, web, APIs.
url: "http://1991.io"

# Build settings
source: ./site
destination: ./dist
markdown: redcarpet
permalink: pretty
