# Site settings
title: thibaultcha
description: >
  Thibault Charbonnier, Kong & OpenResty contributor.
url: "https://chasum.net"

# Build settings
source: ./site
destination: ./dist
permalink: pretty
