# Site settings
title: thibaultcha
description: >
  Thibault Charbonnier, developer. Open-source, iOS, web, APIs.
url: "http://1991.io"

# Build settings
source: ./site
destination: ./dist
permalink: pretty
