# Site settings
title: thibaultcha
url: "https://chasum.net"
# Homepage settings
name: Thibault Charbonnier
description: >
    All things Linux/NGINX/LuaJIT. iOS/Node.js/Frontend in a previous life.
job_title: >
    Principal Engineer @ [Kong Inc.](https://konghq.com)

# Build settings
source: ./site
destination: ./dist
permalink: pretty
