name: Deploy
on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - uses: actions/checkout@v2
      - name: Build
        run: |
          bundle install
          bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: chasum.net
          publish_dir: ./_site
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
